### ISSUE TITLE
Cloud Synology server itself cross the wall?

### ISSUE THREAD

**Issue by iwinstar** [412999826/clash-synology#1]
感谢提供此文档，已参考通过 Docker 方式实现局域网内自动分流代理

但有个问题，此代理对于群晖本身无效。尝试加了如下规则仍然不行
> iptables -t nat -A OUTPUT -p tcp -j clash

**Comment by 412999826** [comment]
试试加这一条，"$dns_port"换成clash的dns监听端口
`iptables -t nat -I OUTPUT -p udp --dport 53 -j --to-port "$dns_port"`

但是我使用该条规则，群晖本身的确可以代理，但是会出现莫名其妙的问题，具体如下：https://github.com/Dreamacro/clash/issues/2103

**Comment by iwinstar** [comment]
感谢回复

我的意思是群晖本机能否顺利执行 `curl https://www.google.com` 之类的验证本机能否正常走代理，我这里是不行的。局域网其他设备可以，只有群晖不行

另外与 UDP 相关的 iptables 规则我都没有加，DNS是直接在群晖跑的AdGuardHome，然后指定 AdGuardHome上游DNS是$synology_host:$dns_port 就可以了

**Comment by 412999826** [comment]
> 感谢回复
> 
> 我的意思是群晖本机能否顺利执行 `curl https://www.google.com` 之类的验证本机能否正常走代理，我这里是不行的。局域网其他设备可以，只有群晖不行
> 
> 另外与 UDP 相关的 iptables 规则我都没有加，DNS是直接在群晖跑的AdGuardHome，然后指定 AdGuardHome上游DNS是$synology_host:$dns_port 就可以了

我知道你说的群晖自身代理的意思。
因为我是fake-ip模式，已经通过iptable将全部fakeip流量走clash代理（如下命令）。
iptables -t nat -A OUTPUT -p tcp -d "$fake_ip_range" -j REDIRECT --to-port "$proxy_port"

所以我那条的指令实际上是让群晖本机的dns转到clash上（dns走udp请求），让clash把dns解析到fake-ip段，就可以实现本机的代理。

**Comment by iwinstar** [comment]
我理解fake-ip只是DNS处理方式的吧，跟本机TCP请求能不能走透明代理没关系？

https://github.com/Dreamacro/clash/issues/555#issuecomment-594624619 这里有一张解决办法，需要自编译iptable xt_owner mod，然后增加一条TCP OUTPUT链

**Comment by 412999826** [comment]
> 

我理解是有的、fakeip只代理了198.18的流量，你正常dns解析是给你域名真实的ip，那这个真实的ip并没有走代理，所以你必须要让clash把域名解析到198网段。

你可以尝试一下添加我的那一条规则

**Comment by 412999826** [comment]
> 我理解fake-ip只是DNS处理方式的吧，跟本机TCP请求能不能走透明代理没关系？
> 
> [Dreamacro/clash#555 (comment)](https://github.com/Dreamacro/clash/issues/555#issuecomment-594624619) 这里有一张解决办法，需要自编译iptable xt_owner mod，然后增加一条TCP OUTPUT链

fakeip已经把198.18段的本机流量做了代理，我在实操中发现只要群晖本机dns的53端口交由clash，让clash把域名解析到198.18 IP段即可实现群晖本机代理（curl也正常）

不过我不用adguard，不知道是否存在冲突。

我的方式是在本机198网段流量已经被代理的前提下，我让clash接管dns，强制把域名解析到198，你的代码是在iptable中，把全部output交由clash，感觉理论应该也可以，建议可以先试试不要adguard，一步步排查。

**Comment by iwinstar** [comment]
我的问题不是DNS哦，群晖本机上是可以拿到正确的DNS解析结果没有污染的。以Google为例，虽有正确的IP但无法与它正常TCP握手，当然就打不开这个网站了

https://github.com/Dreamacro/clash/issues/158 这里也提到了

我比较纳闷按照现有配置你在群晖上能直接访问被屏蔽的服务？看这些issue你应该也会面临同样的问题啊？

**Comment by 412999826** [comment]
> 我的问题不是DNS哦，群晖本机上是可以拿到正确的DNS解析结果没有污染的。以Google为例，虽有正确的IP但无法与它正常TCP握手，当然就打不开这个网站了
> 
> [Dreamacro/clash#158](https://github.com/Dreamacro/clash/issues/158) 这里也提到了
> 
> 我比较纳闷按照现有配置你在群晖上能直接访问被屏蔽的服务？看这些issue你应该也会面临同样的问题啊？

我说的不是dns污染的问题哈，我知道你能拿到正确的ip。

我的意思是你按我的配置方式，output已经代理了198段（你的是全代理了，我确实觉得你的应该也可行，为啥不行不知道了），剩下你让dns把google之类的网站解析到198段（就是我最开始回复的规则），直接就可以curl了。

但是加了我那个指令很多dns无效了，目前经过测试使用如下DNS服务器完全正常：[https://223.5.5.5/dns-query、tls://8.8.4.4:853](https://223.5.5.5/dns-query%E3%80%81tls://8.8.4.4:853)

你尝试用我提供的dns，并且不用adguard，然后加上我给你的规则，看看行不行
iptables -t nat -I OUTPUT -p udp --dport 53 -j --to-port "$dns_port"

至少我这样设置就可以了，但是114之类的dns就都不可用，必须用我给你dns才正常，这个问题我也不知道为什么。

所以你要有空按我的设置设置一下，顺便我也想知道为啥这么设置很多dns就无效了。

**Comment by iwinstar** [comment]
不想用 fake-ip，我认为它带来的问题比解决的问题多～

我的问题已经解决了，记录如下：

1. 参考 https://github.com/sjtuross/syno-iptables/blob/master/BUILD.md 交叉编译出适用 Synology 架构的 `xt_owner.ko`
> 若编译期间遇到`scripts/mod/modpost: not found`或`include/generated/autoconf.h or include/config/auto.conf are missing.`之类的错误，需执行如下命令准备环境
```shell
# 以 apollolake 7.0 为例，其他架构请自行调整
cd /spksrc/kernel/syno-apollolake-7.0/work/linux && make oldconfig && make prepare && make scripts
```
编译`netfilter owner`内核模块只需准备如下环境变量
```shell
export CONFIG_NETFILTER_XT_MATCH_OWNER=m
```
最后编译完成上传群晖后注册此模块
```shell
insmod /lib/modules/xt_owner.ko
```
2. 群晖中增加 clash 用户，Systemd 配置文件中指定以clash用户启动clash服务
```properties
......
[Service]
User=clash
......
```
3. iptables 中增加 OUTPUT 链配置，将群晖本机 clash 进程以外的 TCP 流量 REDIRECT 至 7892 端口
```shell
iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner clash -j REDIRECT --to-port 7892
```

完成，局域网各设备包括群晖本机透明代理均工作正常，DNS解析无污染对国内CDN域名友好

附录：

完整 iptables 规则
```shell
iptables -t nat -N CLASH

iptables -t nat -A CLASH -d 0.0.0.0/8 -j RETURN
iptables -t nat -A CLASH -d 10.0.0.0/8 -j RETURN
iptables -t nat -A CLASH -d 127.0.0.0/8 -j RETURN
iptables -t nat -A CLASH -d 169.254.0.0/16 -j RETURN
iptables -t nat -A CLASH -d 172.16.0.0/12 -j RETURN
iptables -t nat -A CLASH -d 192.168.0.0/16 -j RETURN
iptables -t nat -A CLASH -d 224.0.0.0/4 -j RETURN
iptables -t nat -A CLASH -d 240.0.0.0/4 -j RETURN

iptables -t nat -A CLASH -p tcp -j REDIRECT --to-port 7892
iptables -t nat -A PREROUTING -p tcp -j CLASH
iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner clash -j REDIRECT --to-port 7892
```

完整 Clash DNS 配置
```yaml
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
     geoip: true
     geoip-code: CN
     ipcidr:
       - 240.0.0.0/4
```

**Comment by 412999826** [comment]
> 不想用 fake-ip，我认为它带来的问题比解决的问题多～
> 
> 我的问题已经解决了，记录如下：
> 
> 1. 参考 https://github.com/sjtuross/syno-iptables/blob/master/BUILD.md 交叉编译出适用 Synology 架构的 `xt_owner.ko`
> 
> > 若编译期间遇到`scripts/mod/modpost: not found`或`include/generated/autoconf.h or include/config/auto.conf are missing.`之类的错误，需执行如下命令准备环境
> 
> ```shell
> # 以 apollolake 7.0 为例，其他架构请自行调整
> cd /spksrc/kernel/syno-apollolake-7.0/work/linux && make oldconfig && make prepare && make scripts
> ```
> 
> 编译`netfilter owner`内核模块只需准备如下环境变量
> 
> ```shell
> export CONFIG_NETFILTER_XT_MATCH_OWNER=m
> ```
> 
> 最后编译完成上传群晖后注册此模块
> 
> ```shell
> insmod /lib/modules/xt_owner.ko
> ```
> 
>  2. 群晖中增加 clash 用户，Systemd 配置文件中指定以clash用户启动clash服务
> 
> ```ini
> ......
> [Service]
> User=clash
> ......
> ```
> 
>  3. iptables 中增加 OUTPUT 链配置，将群晖本机 clash 进程以外的 TCP 流量 REDIRECT 至 7892 端口
> 
> ```shell
> iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner clash -j REDIRECT --to-port 7892
> ```
> 
> 完成，局域网各设备包括群晖本机透明代理均工作正常，DNS解析无污染对国内CDN域名友好
> 
> 附录：
> 
> 完整 iptables 规则
> 
> ```shell
> iptables -t nat -N CLASH
> 
> iptables -t nat -A CLASH -d 0.0.0.0/8 -j RETURN
> iptables -t nat -A CLASH -d 10.0.0.0/8 -j RETURN
> iptables -t nat -A CLASH -d 127.0.0.0/8 -j RETURN
> iptables -t nat -A CLASH -d 169.254.0.0/16 -j RETURN
> iptables -t nat -A CLASH -d 172.16.0.0/12 -j RETURN
> iptables -t nat -A CLASH -d 192.168.0.0/16 -j RETURN
> iptables -t nat -A CLASH -d 224.0.0.0/4 -j RETURN
> iptables -t nat -A CLASH -d 240.0.0.0/4 -j RETURN
> 
> iptables -t nat -A CLASH -p tcp -j REDIRECT --to-port 7892
> iptables -t nat -A PREROUTING -p tcp -j CLASH
> iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner clash -j REDIRECT --to-port 7892
> ```
> 
> 完整 Clash DNS 配置
> 
> ```yaml
> dns:
>   enable: true
>   ipv6: false
>   listen: 0.0.0.0:1053
>   enhanced-mode: redir-host
>   default-nameserver:
>     - 119.29.29.29
>     - 223.5.5.5
>   nameserver:
>     - https://doh.pub/dns-query
>     - https://dns.alidns.com/dns-query
>   fallback:
>     - https://1.1.1.1/dns-query
>     - https://dns.google/dns-query
>   fallback-filter:
>      geoip: true
>      geoip-code: CN
>      ipcidr:
>        - 240.0.0.0/4
> ```

解决了就好👍👍👍👍

我不用fakeip的话，网页打开总有延迟，fakeip可以秒开。

然后不论是不是开fakeip，本机需要代理的话我都要加上我之前那个dns规则，但是一旦加上，就会出现很多dns无效的情况，具体如下：
https://github.com/Dreamacro/clash/issues/2103

如果你有空研究的话，我也很想知道是为什么。

**Comment by iwinstar** [comment]
你这条DNS规则导致群晖本机往53端口发起的UDP DNS回环了

请求转到clash后，clash请求114.114.114.114，因为是 UDP 53 端口iptables又转给了clash。很快群晖连接耗尽报了`too many open files`。

所以我理解你只能用走TCP的DNS，UDP默认53端口的都不行。

解决办法也简单，同样用clash用户拉起clash进程。然后iptables不处理clash进程发起的UDP DNS：
```shell
iptables -t nat -I OUTPUT -p udp --dport 53 -m owner ! --uid-owner clash -j clash_dns
```

**Comment by 412999826** [comment]
> 你这条DNS规则导致群晖本机往53端口发起的UDP DNS回环了
> 
> 请求转到clash后，clash请求114.114.114.114，因为是 UDP 53 端口iptables又转给了clash。很快群晖连接耗尽报了`too many open files`。
> 
> 所以我理解你只能用走TCP的DNS，UDP默认53端口的都不行。
> 
> 解决办法也简单，同样用clash用户拉起clash进程。然后iptables不处理clash进程发起的UDP DNS：
> 
> ```shell
> iptables -t nat -I OUTPUT -p udp --dport 53 -m owner ! --uid-owner clash -j clash_dns
> ```

应该就是您说的问题，我也看过clash下面issue说的回环问题，但是因为要用指定用户启动，加上我也没有群晖本体代理的需求，于是我就不想折腾了。

感谢您解开了我的疑惑。
