### ISSUE TITLE
兼容群暉的 DNS 服務實現局域網域名解析

### ISSUE THREAD

**Issue by chunheisiu** [412999826/clash-synology#2]
我照著你的教程成功實現了局域網裡的設備通過代理上網，先感謝大佬！
但是發現如果打開了群暉自帶的 DNS 服務，就會導致域名解析失敗。
由於想通過反向代理為部署在 Docker 上的一些服務（包括 YACD）提供一些域名解析，請問大佬有沒有好的實現方式？

**Comment by 412999826** [comment]
不建议开启群晖的DNS服务，如果你希望劫持一些域名到指定ip，可以在clash的配置文件进行配置，例如：

hosts:
  '*.clash.dev': 127.0.0.1
