### ISSUE TITLE
请问在公网上搭建的，有没有办法保护一下，现在一个IP加端口就能访问，感觉太不安全了，有办法添加密码吗？

### ISSUE THREAD

**Issue by lsxf** [412999826/clash-synology#7]
如题

**Comment by 412999826** [comment]
> 如题

一个端口就能访问啥？9090的clash设置页面么？

**Comment by lsxf** [comment]
> 

设置页面有密码没关系的，我是说IP加端口就直接能代理出去翻墙了，我是公网IP，不知有没有手段能扫描到，这样翻墙流量扛不住啊

**Comment by 412999826** [comment]
> > 
> 
> 
> 
> 设置页面有密码没关系的，我是说IP加端口就直接能代理出去翻墙了，我是公网IP，不知有没有手段能扫描到，这样翻墙流量扛不住啊

我用群晖是采用端口转发的模式，不是采用群晖进行ppoe拨号或者dmz主机的模式，所以只要不转发这个端口就没这个问题。

**Comment by lsxf** [comment]
我现在是光猫桥接，主路由拨号，一个h3c的WIFI6做纯AP，群晖连在主路由上，现在正是需要在外面时也使用群晖的翻墙，所以需要在路由器上转发这个端口，我是请教大咖，有没有办法加个验证或其他方式，而不是现在一个IP加端口就可以用我的翻墙流量了，不知我解释清楚了么

**Comment by lsxf** [comment]
至于为啥不用移动设备自己翻，一方面开着clash之类总之耗电大些，另外，苹果设备不需要买软件也能翻墙了

**Comment by lsxf** [comment]
解决了，是我太小白了，感谢回答哈

配置里添加authentication就可以了

**Comment by 412999826** [comment]
> 解决了，是我太小白了，感谢回答哈
> 
> 
> 
> 配置里添加authentication就可以了

如果你是这个需求，我强烈建议你用群晖的vpn套件，配置一个l2tp服务。
套件需要去群晖海外的站点下载，安全性更有保障，可以和群晖一样设置密码错误自动封锁，同时也可以实现在外面访问家里的设备，如光猫、路由器。

https://www.synology.com/zh-tw/support/download

**Comment by lsxf** [comment]
感谢指点哈，豁然开朗了

请问是指的这个套件么：https://www.synology.com/zh-tw/srm/feature/vpn_plus

**Comment by 412999826** [comment]
> 感谢指点哈，豁然开朗了
> 
> 
> 
> 请问是指的这个套件么：https://www.synology.com/zh-tw/srm/feature/vpn_plus

不是哈，是这个

https://www.synology.com/zh-tw/releaseNote/VPNCenter?model=DS920%2B#7_x_series

下载地址（以ds920举例，请自行更新自己的型号）

https://www.synology.com/zh-tw/support/download/DS920+?version=7.1#packages

**Comment by lsxf** [comment]
感谢感谢，找到了

https://global.synologydownload.com/download/Package/spk/VPNCenter/1.4.7-2901/VPNCenter-x86_64-1.4.7-2901.spk?model=DS918%2B&bays=4&dsm_version=7.1.1&build_number=42962

 再次感谢哈

**Comment by 412999826** [comment]
> 感谢感谢，找到了
> 
> 
> 
> https://global.synologydownload.com/download/Package/spk/VPNCenter/1.4.7-2901/VPNCenter-x86_64-1.4.7-2901.spk?model=DS918%2B&bays=4&dsm_version=7.1.1&build_number=42962
> 
> 
> 
>  再次感谢哈
> 
> 

客气，后续有配置问题可以在交流。个人认为使用群晖的VPN套件，在便捷性、安全性上都更加优秀。

**Comment by lsxf** [comment]
还得麻烦下大佬

“可以由群晖开启dhcp服务器，并将网关和dns指向群晖，即可实现局域网设备的自动全局代理”

之前我是群晖配置好后，其他设备用群晖代理可以正常翻墙，一直没实现自动全局

请问一下，我在主路由的LAN选项里的DHCP配置设置网关是群晖的IP，DNS也是群晖的IP，群晖里也开启了DHCP服务，没能实现自动全局，请问群晖里的DHCP服务要怎样配置，以及是否主路由也配置错了？

**Comment by 412999826** [comment]
> 还得麻烦下大佬
> 
> 
> 
> “可以由群晖开启dhcp服务器，并将网关和dns指向群晖，即可实现局域网设备的自动全局代理”
> 
> 
> 
> 之前我是群晖配置好后，其他设备用群晖代理可以正常翻墙，一直没实现自动全局
> 
> 
> 
> 请问一下，我在主路由的LAN选项里的DHCP配置设置网关是群晖的IP，DNS也是群晖的IP，群晖里也开启了DHCP服务，没能实现自动全局，请问群晖里的DHCP服务要怎样配置，以及是否主路由也配置错了？

dhcp在一个设备开启就可以，如果主路由的dhcp可以自由更改网关和dns，就由主路由开启，网关dns指向群晖。我说让群晖开启dhcp服务主要是因为很多路由器的dhcp不让自由修改网关和dns。

另外你说你不能自动，是不是因为多个域名，产生了多个网段？或者是clash没有接管所有流量？（就是你说的要手动是怎么手动，是直接改了ip设置的dhcp和dns就行，还是必须在网络设置添加代理？）

**Comment by lsxf** [comment]
目前是这样，主路由改了LAN里的网关，指向群晖IP，没改主路由的DNS，关闭了群晖的DHCP，目前可以全局自动翻墙了，但有个问题，只有连接到WIFI才能自动全局翻墙，上另一条外网，连不到VPN，但在和群晖同一个局域网时，用内网IP可以连接上VPN，好奇怪，正在各种试，主路由添加了1701等3个端口的转发了

**Comment by lsxf** [comment]
> > 还得麻烦下大佬
> > “可以由群晖开启dhcp服务器，并将网关和dns指向群晖，即可实现局域网设备的自动全局代理”
> > 之前我是群晖配置好后，其他设备用群晖代理可以正常翻墙，一直没实现自动全局
> > 请问一下，我在主路由的LAN选项里的DHCP配置设置网关是群晖的IP，DNS也是群晖的IP，群晖里也开启了DHCP服务，没能实现自动全局，请问群晖里的DHCP服务要怎样配置，以及是否主路由也配置错了？
> 
> dhcp在一个设备开启就可以，如果主路由的dhcp可以自由更改网关和dns，就由主路由开启，网关dns指向群晖。我说让群晖开启dhcp服务主要是因为很多路由器的dhcp不让自由修改网关和dns。
> 
> 另外你说你不能自动，是不是因为多个域名，产生了多个网段？或者是clash没有接管所有流量？（就是你说的要手动是怎么手动，是直接改了ip设置的dhcp和dns就行，还是必须在网络设置添加代理？）

之前说的手动是必须在网络设计添加代理

**Comment by 412999826** [comment]
> 目前是这样，主路由改了LAN里的网关，指向群晖IP，没改主路由的DNS，关闭了群晖的DHCP，目前可以全局自动翻墙了，但有个问题，只有连接到WIFI才能自动全局翻墙，上另一条外网，连不到VPN，但在和群晖同一个局域网时，用内网IP可以连接上VPN，好奇怪，正在各种试，主路由添加了1701等3个端口的转发了

不太明白你说的“上另一条网”是啥意？另外，VPN在内网是不需要打开的，只有在外面上网的时候，才需要开启vpn，个人觉得你的网络结构可能因为多个路由存在多网段，尽量精简成单一网段。
你现在的结构是：
光猫---主路由拨号---群晖
                               ---华为AP

这样么？你说的另一条网是指链接在哪里？

**Comment by lsxf** [comment]
> > 目前是这样，主路由改了LAN里的网关，指向群晖IP，没改主路由的DNS，关闭了群晖的DHCP，目前可以全局自动翻墙了，但有个问题，只有连接到WIFI才能自动全局翻墙，上另一条外网，连不到VPN，但在和群晖同一个局域网时，用内网IP可以连接上VPN，好奇怪，正在各种试，主路由添加了1701等3个端口的转发了
> 
> 不太明白你说的“上另一条网”是啥意？另外，VPN在内网是不需要打开的，只有在外面上网的时候，才需要开启vpn，个人觉得你的网络结构可能因为多个路由存在多网段，尽量精简成单一网段。 你现在的结构是： 光猫---主路由拨号---群晖 ---华为AP
> 
> 这样么？你说的另一条网是指链接在哪里？

我有两条外网，一条主线路是主路由和群晖所在的，另一条外线，随便接了个无线路由，可以单独上网，两个网络完全没有交叉

那看来，我还是VPN的问题，或者是主路由端口转发的问题，我再试试

**Comment by 412999826** [comment]
> > > 目前是这样，主路由改了LAN里的网关，指向群晖IP，没改主路由的DNS，关闭了群晖的DHCP，目前可以全局自动翻墙了，但有个问题，只有连接到WIFI才能自动全局翻墙，上另一条外网，连不到VPN，但在和群晖同一个局域网时，用内网IP可以连接上VPN，好奇怪，正在各种试，主路由添加了1701等3个端口的转发了
> 
> > 
> 
> > 不太明白你说的“上另一条网”是啥意？另外，VPN在内网是不需要打开的，只有在外面上网的时候，才需要开启vpn，个人觉得你的网络结构可能因为多个路由存在多网段，尽量精简成单一网段。 你现在的结构是： 光猫---主路由拨号---群晖 ---华为AP
> 
> > 
> 
> > 这样么？你说的另一条网是指链接在哪里？
> 
> 
> 
> 我有两条外网，一条主线路是主路由和群晖所在的，另一条外线，随便接了个无线路由，可以单独上网，两个网络完全没有交叉
> 
> 
> 
> 那看来，我还是VPN的问题，或者是主路由端口转发的问题，我再试试

也就是你拉了2条宽带，群晖在的那条已经实现了全局自动；另一条手机vpn直接连接不成功？那这个可能是端口转发的问题，还有种极端情况，就是运营商把端口封了

**Comment by 412999826** [comment]
> > > 目前是这样，主路由改了LAN里的网关，指向群晖IP，没改主路由的DNS，关闭了群晖的DHCP，目前可以全局自动翻墙了，但有个问题，只有连接到WIFI才能自动全局翻墙，上另一条外网，连不到VPN，但在和群晖同一个局域网时，用内网IP可以连接上VPN，好奇怪，正在各种试，主路由添加了1701等3个端口的转发了
> 
> > 
> 
> > 不太明白你说的“上另一条网”是啥意？另外，VPN在内网是不需要打开的，只有在外面上网的时候，才需要开启vpn，个人觉得你的网络结构可能因为多个路由存在多网段，尽量精简成单一网段。 你现在的结构是： 光猫---主路由拨号---群晖 ---华为AP
> 
> > 
> 
> > 这样么？你说的另一条网是指链接在哪里？
> 
> 
> 
> 我有两条外网，一条主线路是主路由和群晖所在的，另一条外线，随便接了个无线路由，可以单独上网，两个网络完全没有交叉
> 
> 
> 
> 那看来，我还是VPN的问题，或者是主路由端口转发的问题，我再试试


为避免别的干扰，你可以试试 蜂窝数据下，vpn可否连上，如果都不行那肯定是群晖那条网络端口转发问题。
如果蜂窝数据可以，那你得看看另外一条宽带的路由器防火墙设置了

**Comment by lsxf** [comment]
> > > > 目前是这样，主路由改了LAN里的网关，指向群晖IP，没改主路由的DNS，关闭了群晖的DHCP，目前可以全局自动翻墙了，但有个问题，只有连接到WIFI才能自动全局翻墙，上另一条外网，连不到VPN，但在和群晖同一个局域网时，用内网IP可以连接上VPN，好奇怪，正在各种试，主路由添加了1701等3个端口的转发了
> > 
> > 
> > > 
> > 
> > 
> > > 不太明白你说的“上另一条网”是啥意？另外，VPN在内网是不需要打开的，只有在外面上网的时候，才需要开启vpn，个人觉得你的网络结构可能因为多个路由存在多网段，尽量精简成单一网段。 你现在的结构是： 光猫---主路由拨号---群晖 ---华为AP
> > 
> > 
> > > 
> > 
> > 
> > > 这样么？你说的另一条网是指链接在哪里？
> > 
> > 
> > 我有两条外网，一条主线路是主路由和群晖所在的，另一条外线，随便接了个无线路由，可以单独上网，两个网络完全没有交叉
> > 那看来，我还是VPN的问题，或者是主路由端口转发的问题，我再试试
> 
> 为避免别的干扰，你可以试试 蜂窝数据下，vpn可否连上，如果都不行那肯定是群晖那条网络端口转发问题。 如果蜂窝数据可以，那你得看看另外一条宽带的路由器防火墙设置了
> 
> 另外，vpn在外面要能用得用群晖的公网ip或者域名，这部分设置要注意

感谢提醒，又折腾了下，现在蛮奇怪的

两台手机，一个小米连不上VPN，华为可以，但连上以后，大概1分钟就掉下来，另外，好像也没有自动全局，连上了所有网站都打不开了

电脑好像一直不行，怎么都连接不上，换手机热点也不行，我打算换台电脑试下

不好意思，我这小白给大佬添麻烦了

**Comment by lsxf** [comment]
终于推进了一步，不知为啥群晖的VPN只能在内网用，主路由怎么设置端口转发都不行，正好看主路由里有VPN功能（TPLINK TLR479G+），就试了下，现在能VPN连接上来了，但不知为啥连上来以后的连接网关是0000，不是我之前在主路由的设置的.8，就差这一步了，继续折腾:DDD

**Comment by 412999826** [comment]
> 终于推进了一步，不知为啥群晖的VPN只能在内网用，主路由怎么设置端口转发都不行，正好看主路由里有VPN功能（TPLINK TLR479G+），就试了下，现在能VPN连接上来了，但不知为啥连上来以后的连接网关是0000，不是我之前在主路由的设置的.8，就差这一步了，继续折腾:DDD

用tplink的vpn功能应该只能在外面实现“回家”，无法实现科学的效果。你的描述其实还是很像端口转发没有成功，所以内网可以连上外网不行，另外要转发的端口是udp，不是tcp，这个要提醒你下

**Comment by lsxf** [comment]
> > 终于推进了一步，不知为啥群晖的VPN只能在内网用，主路由怎么设置端口转发都不行，正好看主路由里有VPN功能（TPLINK TLR479G+），就试了下，现在能VPN连接上来了，但不知为啥连上来以后的连接网关是0000，不是我之前在主路由的设置的.8，就差这一步了，继续折腾:DDD
> 
> 用tplink的vpn功能应该只能在外面实现“回家”，无法实现科学的效果。你的描述其实还是很像端口转发没有成功，所以内网可以连上外网不行，另外要转发的端口是udp，不是tcp，这个要提醒你下

感谢耐心细致的回复哈

特别奇怪，我这个路由上开了很多端口，用telnet测试都正常，唯独1701、500、4500这三个不行，怀疑是tplink路由器的问题，我再想想办法，是不是因为路由器本身有VPN功能，这3个端口不放开了？

**Comment by 412999826** [comment]
> > > 终于推进了一步，不知为啥群晖的VPN只能在内网用，主路由怎么设置端口转发都不行，正好看主路由里有VPN功能（TPLINK TLR479G+），就试了下，现在能VPN连接上来了，但不知为啥连上来以后的连接网关是0000，不是我之前在主路由的设置的.8，就差这一步了，继续折腾:DDD
> 
> > 
> 
> > 用tplink的vpn功能应该只能在外面实现“回家”，无法实现科学的效果。你的描述其实还是很像端口转发没有成功，所以内网可以连上外网不行，另外要转发的端口是udp，不是tcp，这个要提醒你下
> 
> 
> 
> 感谢耐心细致的回复哈
> 
> 
> 
> 特别奇怪，我这个路由上开了很多端口，用telnet测试都正常，唯独1701、500、4500这三个不行，怀疑是tplink路由器的问题，我再想想办法，是不是因为路由器本身有VPN功能，这3个端口不放开了？


这倒是很有可能，因为和自身服务冲突了。建议尝试换个路由器，排除下变量

**Comment by lsxf** [comment]
> > > > 终于推进了一步，不知为啥群晖的VPN只能在内网用，主路由怎么设置端口转发都不行，正好看主路由里有VPN功能（TPLINK TLR479G+），就试了下，现在能VPN连接上来了，但不知为啥连上来以后的连接网关是0000，不是我之前在主路由的设置的.8，就差这一步了，继续折腾:DDD
> > 
> > 
> > > 
> > 
> > 
> > > 用tplink的vpn功能应该只能在外面实现“回家”，无法实现科学的效果。你的描述其实还是很像端口转发没有成功，所以内网可以连上外网不行，另外要转发的端口是udp，不是tcp，这个要提醒你下
> > 
> > 
> > 感谢耐心细致的回复哈
> > 特别奇怪，我这个路由上开了很多端口，用telnet测试都正常，唯独1701、500、4500这三个不行，怀疑是tplink路由器的问题，我再想想办法，是不是因为路由器本身有VPN功能，这3个端口不放开了？
> 
> 这倒是很有可能，因为和自身服务冲突了。建议尝试换个路由器，排除下变量

终于调通了，回来汇报下
路由器没换，但恢复了下出厂设置，只通上外网就配置转发，测试成功了，看来是之前不知道什么配置惹的祸，感谢一直耐心的指导哈，感谢感谢
