### ISSUE TITLE
升级DSM7.2后，代理失效了，请问大佬遇到同样问题了吗？

### ISSUE THREAD

**Issue by lsxf** [412999826/clash-synology#8]
我按照步骤又走了一遍，也没能成功，大佬指点下哈

**Comment by 412999826** [comment]
先用'systemctl status clash'查询一下到底是clash没有运行起来，还是运行起来了无法上网

**Comment by lsxf** [comment]
May 30 09:21:43 jms clash[8627]: 2023/05/30 09:21:43 http: Accept error: accept tcp [::]:9898: accept4: too many open files; retrying in 160ms
May 30 09:21:43 jms clash[8627]: 2023/05/30 09:21:43 http: Accept error: accept tcp [::]:9898: accept4: too many open files; retrying in 320ms

**Comment by lsxf** [comment]
运行起来了，但报这个错不知为啥

**Comment by 412999826** [comment]
> 运行起来了，但报这个错不知为啥
配置文件 tun模式中，这2行可以尝试删除试试
auto-redir: true
auto-route: true

**Comment by lsxf** [comment]
> > 运行起来了，但报这个错不知为啥
> 
> 配置文件 tun模式中，这2行可以尝试删除试试 auto-redir: true auto-route: true

我的配置里只有这个auto-route: true
注释了就好了，感谢感谢哈，大佬就是大佬
